import type { KettleHass } from './types';

const EN = {
  'common.kettle': 'Kettle',
  'common.manual': 'Manual',
  'common.boil': 'Boil',
  'common.start': 'Start',
  'common.stop': 'Stop',
  'common.tap_again': 'Tap again',
  'duration.hour': '{count} h',
  'duration.minute': '{count} min',
  'status.ready': 'Ready',
  'status.heating': 'Heating',
  'status.boiling': 'Boiling',
  'status.cooling': 'Cooling',
  'status.keeping_warm': 'Keeping warm',
  'status.lifted': 'Lifted from base',
  'status.fault': 'Fault · code {code}',
  'status.unavailable': 'Unavailable',
  'card.select_entity': 'Select a yunmi.kettle.v19 water heater entity.',
  'card.loading': 'Kettle is loading',
  'card.starting': 'Home Assistant is starting. Not everything may be available yet.',
  'card.open_dialog': 'Open kettle dialog',
  'editor.entity': 'Kettle entity',
  'editor.name': 'Title',
  'editor.icon': 'Icon',
  'editor.show_presets': 'Show programs',
  'editor.show_controls': 'Show Boil and Stop controls',
  'editor.program_icons': 'Program icons',
  'editor.program_icons_description': 'Choose an icon for each preset discovered from Xiaomi Home.',
  'editor.preset_icon': '{name} icon',
  'dialog.resolve_error': 'Unable to resolve this kettle’s entities.',
  'dialog.command_failed': 'Kettle command failed',
  'dialog.stop_unavailable': 'Stop is unavailable',
  'dialog.tap_again_to_boil': 'Tap again to boil',
  'dialog.tap_again_preset': 'Tap again · {name}',
  'dialog.target_summary': 'Target {temperature}°C',
  'dialog.keep_summary': 'Keep {temperature}°C',
  'dialog.left_summary': '{duration} left',
  'dialog.open_history': 'Open temperature history',
  'dialog.stop_kettle': 'Stop kettle',
  'dialog.no_presets': 'No kettle presets available',
  'dialog.target_temperature': 'Target temperature',
  'dialog.target_temperature_help': 'Choose from 40 to 99°C',
  'dialog.keep_warm': 'Keep warm',
  'dialog.keep_warm_help': 'Maintain temperature after heating',
  'dialog.temperature': 'Temperature',
  'dialog.keep_warm_target': 'Keep-warm target',
  'dialog.keep_warm_temperature': 'Keep-warm temperature',
  'dialog.duration': 'Duration',
  'dialog.duration_help': '1 to 24 hours',
  'dialog.keep_warm_duration': 'Keep-warm duration',
  'dialog.preferences': 'Preferences',
  'dialog.kettle_position': 'Kettle position',
  'dialog.seated': 'Seated on base',
  'dialog.kept_warm': 'Kept warm',
  'dialog.boiling_reminder': 'Boiling reminder',
  'dialog.keep_warm_reminder': 'Keep-warm reminder',
  'dialog.resume_after_lifting': 'Resume after lifting',
  'dialog.resume_after_lifting_help': 'Remember the active keep-warm temperature',
  'dialog.custom_knob': 'Custom knob temperature',
  'dialog.do_not_disturb': 'Do not disturb',
} as const;

type TranslationKey = keyof typeof EN;

const RU: Record<TranslationKey, string> = {
  'common.kettle': 'Чайник',
  'common.manual': 'Вручную',
  'common.boil': 'Вскипятить',
  'common.start': 'Запустить',
  'common.stop': 'Остановить',
  'common.tap_again': 'Нажмите ещё раз',
  'duration.hour': '{count} ч',
  'duration.minute': '{count} мин',
  'status.ready': 'Готов',
  'status.heating': 'Нагрев',
  'status.boiling': 'Кипячение',
  'status.cooling': 'Охлаждение',
  'status.keeping_warm': 'Поддержание температуры',
  'status.lifted': 'Снят с подставки',
  'status.fault': 'Ошибка · код {code}',
  'status.unavailable': 'Недоступен',
  'card.select_entity': 'Выберите сущность водонагревателя yunmi.kettle.v19.',
  'card.loading': 'Чайник загружается',
  'card.starting': 'Home Assistant запускается. Некоторые функции пока могут быть недоступны.',
  'card.open_dialog': 'Открыть диалог чайника',
  'editor.entity': 'Сущность чайника',
  'editor.name': 'Заголовок',
  'editor.icon': 'Значок',
  'editor.show_presets': 'Показывать программы',
  'editor.show_controls': 'Показывать кнопки кипячения и остановки',
  'editor.program_icons': 'Значки программ',
  'editor.program_icons_description': 'Выберите значок для каждой предустановки из Xiaomi Home.',
  'editor.preset_icon': 'Значок «{name}»',
  'dialog.resolve_error': 'Не удалось определить сущности этого чайника.',
  'dialog.command_failed': 'Не удалось выполнить команду чайника',
  'dialog.stop_unavailable': 'Остановка недоступна',
  'dialog.tap_again_to_boil': 'Нажмите ещё раз для кипячения',
  'dialog.tap_again_preset': 'Нажмите ещё раз · {name}',
  'dialog.target_summary': 'Цель {temperature}°C',
  'dialog.keep_summary': 'Поддержание {temperature}°C',
  'dialog.left_summary': 'осталось {duration}',
  'dialog.open_history': 'Открыть историю температуры',
  'dialog.stop_kettle': 'Остановить чайник',
  'dialog.no_presets': 'Нет доступных программ чайника',
  'dialog.target_temperature': 'Целевая температура',
  'dialog.target_temperature_help': 'Выберите от 40 до 99°C',
  'dialog.keep_warm': 'Поддержание температуры',
  'dialog.keep_warm_help': 'Поддерживать температуру после нагрева',
  'dialog.temperature': 'Температура',
  'dialog.keep_warm_target': 'Целевая температура поддержания',
  'dialog.keep_warm_temperature': 'Температура поддержания',
  'dialog.duration': 'Длительность',
  'dialog.duration_help': 'От 1 до 24 часов',
  'dialog.keep_warm_duration': 'Длительность поддержания',
  'dialog.preferences': 'Настройки',
  'dialog.kettle_position': 'Положение чайника',
  'dialog.seated': 'На подставке',
  'dialog.kept_warm': 'Поддерживается тёплым',
  'dialog.boiling_reminder': 'Напоминание о закипании',
  'dialog.keep_warm_reminder': 'Напоминание о поддержании температуры',
  'dialog.resume_after_lifting': 'Возобновление после снятия',
  'dialog.resume_after_lifting_help': 'Запомнить активную температуру поддержания',
  'dialog.custom_knob': 'Пользовательская температура регулятора',
  'dialog.do_not_disturb': 'Не беспокоить',
};

export function translate(
  language: string | undefined,
  key: TranslationKey,
  replacements: Record<string, string | number> = {},
): string {
  const translations = language?.toLowerCase().startsWith('ru') ? RU : EN;
  return Object.entries(replacements).reduce(
    (value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)),
    translations[key],
  );
}

export function localize(
  hass: KettleHass | undefined,
  key: TranslationKey,
  replacements?: Record<string, string | number>,
): string {
  return translate(hass?.locale?.language, key, replacements);
}
